#!/bin/bash

echo "================================================="
echo "   SCREENSHOT TOOLKIT - INSTALLATION COMPLETE"
echo "================================================="
echo ""
echo "SCRIPTS INSTALLED:"
echo "  take_full_screenshot     - Full screen screenshot"
echo "  take_area_screenshot     - Select area screenshot"
echo "  take_window_screenshot   - Active window screenshot"
echo "  take_size_screenshot     - Main script (used by others)"
echo ""
echo "USAGE:"
echo "  take_full_screenshot"
echo "  take_area_screenshot"
echo "  take_window_screenshot"
echo ""
echo "  take_size_screenshot [geometry]"
echo "    Example: take_size_screenshot \"100,100 800x600\""
echo ""
echo "================================================="
echo "CONFIGURATION FILES:"
echo "================================================="
echo ""
echo "1. ~/.config/screenshot_class_map.txt"
echo "   Maps window class names to readable names for screenshots."
echo ""
echo "   Format:"
echo "     class_name=Pretty Name"
echo ""
echo "   Example:"
echo "     org.qutebrowser.qutebrowser=Qutebrowser"
echo "     Alacritty=Terminal"
echo "     code-oss=VS Code"
echo ""
echo "   If a class is not listed, the script will try to find the"
echo "   application name from .desktop files."
echo ""
echo "2. ~/.config/steam_apps.txt"
echo "   Maps Steam App IDs to game names."
echo ""
echo "   Format:"
echo "     app_id=Game Name"
echo ""
echo "   Example:"
echo "     730=Counter-Strike 2"
echo "     10=Counter-Strike"
echo ""
echo "================================================="
echo "DEPENDENCIES:"
echo "================================================="
echo ""
echo "Required:"
echo "  - hyprctl (Hyprland)"
echo "  - grim"
echo "  - slurp"
echo "  - jq"
echo "  - wl-clipboard (wl-copy)"
echo "  - libnotify (notify-send)"
echo "  - pipewire (pw-play for sound)"
echo ""
echo "Optional:"
echo "  - xdg-utils (xdg-open for opening files)"
echo "  - findutils (find command for symlink management)"
echo ""
echo "================================================="
echo "TIPS:"
echo "================================================="
echo ""
echo "  - Screenshots are saved to ~/Pictures/Screenshots/"
echo "  - Screenshots are symlinked in ~/Pictures/Screenshots/Massive/"
echo "  - Screenshots are copied to clipboard automatically"
echo "  - A sound is played when screenshot is taken"
echo "  - Notification includes actions: Show, Open, Delete"
echo ""
echo "NOTIFICATION ACTIONS:"
echo "  - Show   : Opens the screenshot folder"
echo "  - Open   : Opens the screenshot with default viewer"
echo "  - Delete : Removes the screenshot"
echo ""
echo "================================================="
echo "To add custom sound, edit the pw-play path in scripts."
echo ""
echo "To disable sound, comment out or remove the pw-play line."
echo ""
echo "================================================="
echo "Full documentation in README"
echo ""
echo "================================================="
echo "Installation complete!"
echo "================================================="
